/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiTokenCreate : Label bound tokens with their account + membership status (spec §4.2).  A dark deployment (flag off) with only personal rows keeps the exact pre-feature response shape; a bound row is always labeled so it cannot be mistaken for a personal token even after an emergency disable.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenCreate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<models::ScopeEnum>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "account", deserialize_with = "Option::deserialize")]
    pub account: Option<String>,
    #[serde(rename = "membership_status", deserialize_with = "Option::deserialize")]
    pub membership_status: Option<String>,
}

impl ApiTokenCreate {
    /// Label bound tokens with their account + membership status (spec §4.2).  A dark deployment (flag off) with only personal rows keeps the exact pre-feature response shape; a bound row is always labeled so it cannot be mistaken for a personal token even after an emergency disable.
    pub fn new(id: i32, name: String, key: String, created: String, account: Option<String>, membership_status: Option<String>) -> ApiTokenCreate {
        ApiTokenCreate {
            id,
            name,
            scope: None,
            key,
            created,
            account,
            membership_status,
        }
    }
}

