/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenCreate {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<models::ScopeEnum>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "created")]
    pub created: String,
}

impl ApiTokenCreate {
    pub fn new(id: i32, name: String, key: String, created: String) -> ApiTokenCreate {
        ApiTokenCreate {
            id,
            name,
            scope: None,
            key,
            created,
        }
    }
}

