/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenList {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scope")]
    pub scope: models::ScopeEnum,
    #[serde(rename = "key_prefix")]
    pub key_prefix: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "last_used", deserialize_with = "Option::deserialize")]
    pub last_used: Option<String>,
    #[serde(rename = "request_count")]
    pub request_count: i32,
}

impl ApiTokenList {
    pub fn new(id: i32, name: String, scope: models::ScopeEnum, key_prefix: String, created: String, last_used: Option<String>, request_count: i32) -> ApiTokenList {
        ApiTokenList {
            id,
            name,
            scope,
            key_prefix,
            created,
            last_used,
            request_count,
        }
    }
}

