/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachIpv6Response {
    #[serde(rename = "attached")]
    pub attached: bool,
    #[serde(rename = "reboot_required")]
    pub reboot_required: bool,
    #[serde(rename = "rebooted")]
    pub rebooted: bool,
}

impl AttachIpv6Response {
    pub fn new(attached: bool, reboot_required: bool, rebooted: bool) -> AttachIpv6Response {
        AttachIpv6Response {
            attached,
            reboot_required,
            rebooted,
        }
    }
}

