/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bucket {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "quota_gb")]
    pub quota_gb: i32,
    #[serde(rename = "used_bytes")]
    pub used_bytes: i32,
    #[serde(rename = "object_count")]
    pub object_count: i32,
    #[serde(rename = "public_read")]
    pub public_read: bool,
    #[serde(rename = "status")]
    pub status: models::StatusA57Enum,
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "created")]
    pub created: String,
}

impl Bucket {
    pub fn new(id: i32, name: String, full_name: String, quota_gb: i32, used_bytes: i32, object_count: i32, public_read: bool, status: models::StatusA57Enum, endpoint: String, region: String, created: String) -> Bucket {
        Bucket {
            id,
            name,
            full_name,
            quota_gb,
            used_bytes,
            object_count,
            public_read,
            status,
            endpoint,
            region,
            created,
        }
    }
}

