/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BucketCredentials {
    #[serde(rename = "bucket")]
    pub bucket: String,
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "access_key")]
    pub access_key: String,
    #[serde(rename = "secret_key")]
    pub secret_key: String,
}

impl BucketCredentials {
    pub fn new(bucket: String, endpoint: String, region: String, access_key: String, secret_key: String) -> BucketCredentials {
        BucketCredentials {
            bucket,
            endpoint,
            region,
            access_key,
            secret_key,
        }
    }
}

