/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterAdd {
    #[serde(rename = "cluster_type")]
    pub cluster_type: models::ClusterTypeEnum,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID or slug
    #[serde(rename = "resource_pool_package")]
    pub resource_pool_package: String,
    #[serde(rename = "resource_pool_size", skip_serializing_if = "Option::is_none")]
    pub resource_pool_size: Option<i32>,
    #[serde(rename = "kube_version", skip_serializing_if = "Option::is_none")]
    pub kube_version: Option<models::KubeVersionEnum>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::FeaturesEnum>>,
    #[serde(rename = "enable_gateway_api", skip_serializing_if = "Option::is_none")]
    pub enable_gateway_api: Option<bool>,
}

impl ClusterAdd {
    pub fn new(cluster_type: models::ClusterTypeEnum, resource_pool_package: String) -> ClusterAdd {
        ClusterAdd {
            cluster_type,
            name: None,
            resource_pool_package,
            resource_pool_size: None,
            kube_version: None,
            features: None,
            enable_gateway_api: None,
        }
    }
}

