/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClusterEncryptionOperation : One encryption change, as the customer sees it.  ``verification_result`` is deliberately absent: the evidence is published once, sanitised, as the state's ``per_node`` -- two copies of a JSON column are two places for key material to escape from.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterEncryptionOperation {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "requested_mode")]
    pub requested_mode: String,
    #[serde(rename = "previous_mode")]
    pub previous_mode: String,
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "override_unverifiable")]
    pub override_unverifiable: bool,
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "finished_at", deserialize_with = "Option::deserialize")]
    pub finished_at: Option<String>,
}

impl ClusterEncryptionOperation {
    /// One encryption change, as the customer sees it.  ``verification_result`` is deliberately absent: the evidence is published once, sanitised, as the state's ``per_node`` -- two copies of a JSON column are two places for key material to escape from.
    pub fn new(id: i32, kind: String, status: String, requested_mode: String, previous_mode: String, reason: Reason, message: String, override_unverifiable: bool, request_id: String, created_at: String, finished_at: Option<String>) -> ClusterEncryptionOperation {
        ClusterEncryptionOperation {
            id,
            kind,
            status,
            requested_mode,
            previous_mode,
            reason,
            message,
            override_unverifiable,
            request_id,
            created_at,
            finished_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "feature_unavailable")]
    FeatureUnavailable,
    #[serde(rename = "cluster_operation_in_progress")]
    ClusterOperationInProgress,
    #[serde(rename = "resource_not_active")]
    ResourceNotActive,
    #[serde(rename = "cluster_not_provisioned")]
    ClusterNotProvisioned,
    #[serde(rename = "invalid_encryption_mode")]
    InvalidEncryptionMode,
    #[serde(rename = "workload_restart_ack_required")]
    WorkloadRestartAckRequired,
    #[serde(rename = "encryption_state_unknown")]
    EncryptionStateUnknown,
    #[serde(rename = "encryption_already_in_requested_mode")]
    EncryptionAlreadyInRequestedMode,
    #[serde(rename = "reconcile_requires_staff")]
    ReconcileRequiresStaff,
    #[serde(rename = "reconcile_requires_unknown_state")]
    ReconcileRequiresUnknownState,
    #[serde(rename = "cilium_version_mismatch")]
    CiliumVersionMismatch,
    #[serde(rename = "kernel_wireguard_unavailable")]
    KernelWireguardUnavailable,
    #[serde(rename = "kernel_nodes_unknown")]
    KernelNodesUnknown,
    #[serde(rename = "helm_upgrade_failed")]
    HelmUpgradeFailed,
    #[serde(rename = "helm_rollback_failed")]
    HelmRollbackFailed,
    #[serde(rename = "cilium_rollout_failed")]
    CiliumRolloutFailed,
    #[serde(rename = "cilium_node_key_missing")]
    CiliumNodeKeyMissing,
    #[serde(rename = "cilium_peer_verification_failed")]
    CiliumPeerVerificationFailed,
    #[serde(rename = "cilium_agent_unreadable")]
    CiliumAgentUnreadable,
    #[serde(rename = "cilium_agent_state_mismatch")]
    CiliumAgentStateMismatch,
    #[serde(rename = "cilium_encryption_not_active")]
    CiliumEncryptionNotActive,
    #[serde(rename = "cilium_encryption_still_active")]
    CiliumEncryptionStillActive,
    #[serde(rename = "cilium_nodes_unknown")]
    CiliumNodesUnknown,
    #[serde(rename = "cilium_mode_unsupported")]
    CiliumModeUnsupported,
    #[serde(rename = "cilium_verification_misconfigured")]
    CiliumVerificationMisconfigured,
    #[serde(rename = "restart_recheck_failed")]
    RestartRecheckFailed,
    #[serde(rename = "platform_restart_incomplete")]
    PlatformRestartIncomplete,
    #[serde(rename = "encryption_task_aborted")]
    EncryptionTaskAborted,
    #[serde(rename = "dispatch_pending")]
    DispatchPending,
    #[serde(rename = "")]
    Empty,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::FeatureUnavailable
    }
}

