/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterDetail {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "status")]
    pub status: models::StatusA57Enum,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "cluster_type")]
    pub cluster_type: String,
    #[serde(rename = "kube_version")]
    pub kube_version: String,
    #[serde(rename = "price_per_month")]
    pub price_per_month: String,
    #[serde(rename = "price_per_hour")]
    pub price_per_hour: String,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<models::FeaturesEnum>>,
    #[serde(rename = "features_ready")]
    pub features_ready: bool,
    #[serde(rename = "kubeconfig_valid_until")]
    pub kubeconfig_valid_until: String,
    #[serde(rename = "ipv4_address")]
    pub ipv4_address: String,
    #[serde(rename = "protected", skip_serializing_if = "Option::is_none")]
    pub protected: Option<bool>,
    #[serde(rename = "talos_version")]
    pub talos_version: String,
    #[serde(rename = "talos_upgrade_available")]
    pub talos_upgrade_available: String,
    #[serde(rename = "talos_next_version")]
    pub talos_next_version: String,
}

impl ClusterDetail {
    pub fn new(id: i32, status: models::StatusA57Enum, cluster_type: String, kube_version: String, price_per_month: String, price_per_hour: String, features_ready: bool, kubeconfig_valid_until: String, ipv4_address: String, talos_version: String, talos_upgrade_available: String, talos_next_version: String) -> ClusterDetail {
        ClusterDetail {
            id,
            status,
            name: None,
            cluster_type,
            kube_version,
            price_per_month,
            price_per_hour,
            features: None,
            features_ready,
            kubeconfig_valid_until,
            ipv4_address,
            protected: None,
            talos_version,
            talos_upgrade_available,
            talos_next_version,
        }
    }
}

