/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactsUpdate {
    /// Contact type to update  * `registrant` - registrant * `admin` - admin * `tech` - tech * `billing` - billing
    #[serde(rename = "contact_type")]
    pub contact_type: models::ContactTypeEnum,
    /// ID of DomainRegistrant to use
    #[serde(rename = "registrant_id")]
    pub registrant_id: i32,
}

impl ContactsUpdate {
    pub fn new(contact_type: models::ContactTypeEnum, registrant_id: i32) -> ContactsUpdate {
        ContactsUpdate {
            contact_type,
            registrant_id,
        }
    }
}

