/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DedicatedServer : Read-only serializer for dedicated server services.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DedicatedServer {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "status")]
    pub status: models::ServiceStatusEnum,
    /// Euro without TVA
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "next_invoice")]
    pub next_invoice: chrono::NaiveDate,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "billing_cycle")]
    pub billing_cycle: String,
    #[serde(rename = "server_status", deserialize_with = "Option::deserialize")]
    pub server_status: Option<Box<models::DedicatedServerStatus>>,
    #[serde(rename = "ips")]
    pub ips: Vec<models::DedicatedServerIp>,
    #[serde(rename = "os_name", deserialize_with = "Option::deserialize")]
    pub os_name: Option<String>,
}

impl DedicatedServer {
    /// Read-only serializer for dedicated server services.
    pub fn new(id: i32, hostname: String, status: models::ServiceStatusEnum, price: String, next_invoice: chrono::NaiveDate, created: String, billing_cycle: String, server_status: Option<models::DedicatedServerStatus>, ips: Vec<models::DedicatedServerIp>, os_name: Option<String>) -> DedicatedServer {
        DedicatedServer {
            id,
            hostname,
            status,
            price,
            next_invoice,
            created,
            billing_cycle,
            server_status: if let Some(x) = server_status {Some(Box::new(x))} else {None},
            ips,
            os_name,
        }
    }
}

