/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deposit {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "status")]
    pub status: models::DepositStatusEnum,
    /// Fara TVA
    #[serde(rename = "amount")]
    pub amount: String,
    /// TVA
    #[serde(rename = "vat_value")]
    pub vat_value: String,
    #[serde(rename = "vat_percentage")]
    pub vat_percentage: i32,
    /// Cu TVA
    #[serde(rename = "total")]
    pub total: String,
    #[serde(rename = "created")]
    pub created: String,
}

impl Deposit {
    pub fn new(id: i32, status: models::DepositStatusEnum, amount: String, vat_value: String, vat_percentage: i32, total: String, created: String) -> Deposit {
        Deposit {
            id,
            status,
            amount,
            vat_value,
            vat_percentage,
            total,
            created,
        }
    }
}

