/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsRecordCreate : Validate input for creating or editing a DNS record.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsRecordCreate {
    /// Record hostname (use '@' or leave empty for zone apex).
    #[serde(rename = "name")]
    pub name: String,
    /// Time to live in seconds.
    #[serde(rename = "ttl")]
    pub ttl: i32,
    /// DNS record type.  * `A` - A * `AAAA` - AAAA * `TYPE257` - TYPE257 * `CNAME` - CNAME * `MX` - MX * `SRV` - SRV * `TXT` - TXT
    #[serde(rename = "type")]
    pub r#type: models::DnsRecordCreateTypeEnum,
    /// IPv4/IPv6 address (A/AAAA).
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Canonical name (CNAME).
    #[serde(rename = "cname", skip_serializing_if = "Option::is_none")]
    pub cname: Option<String>,
    /// Mail exchange host (MX).
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// MX preference / priority.
    #[serde(rename = "preference", skip_serializing_if = "Option::is_none")]
    pub preference: Option<i32>,
    /// TXT record data.
    #[serde(rename = "txtdata", skip_serializing_if = "Option::is_none")]
    pub txtdata: Option<String>,
    /// Unencoded TXT value.
    #[serde(rename = "unencoded", skip_serializing_if = "Option::is_none")]
    pub unencoded: Option<String>,
    /// SRV target host.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    /// SRV priority.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// SRV weight.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    /// SRV port.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// CAA flag (TYPE257).
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<i32>,
    /// CAA tag (TYPE257).
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// CAA value (TYPE257).
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Line number of existing record to edit. Omit to add a new record.
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<i32>,
}

impl DnsRecordCreate {
    /// Validate input for creating or editing a DNS record.
    pub fn new(name: String, ttl: i32, r#type: models::DnsRecordCreateTypeEnum) -> DnsRecordCreate {
        DnsRecordCreate {
            name,
            ttl,
            r#type,
            address: None,
            cname: None,
            exchange: None,
            preference: None,
            txtdata: None,
            unencoded: None,
            target: None,
            priority: None,
            weight: None,
            port: None,
            flag: None,
            tag: None,
            value: None,
            line: None,
        }
    }
}

