/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsGlue : A glue / \"personal DNS\" record: registers a child nameserver host at the registry as ``<name>.<domain>`` pointing at ``ip`` (and optional ``ip2``). Required before another domain can delegate to that nameserver.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsGlue {
    /// only subdomain part
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "ip2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip2: Option<Option<String>>,
}

impl DnsGlue {
    /// A glue / \"personal DNS\" record: registers a child nameserver host at the registry as ``<name>.<domain>`` pointing at ``ip`` (and optional ``ip2``). Required before another domain can delegate to that nameserver.
    pub fn new(name: String, ip: String) -> DnsGlue {
        DnsGlue {
            name,
            ip,
            ip2: None,
        }
    }
}

