/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsRecord : Read-only representation of a DNS record from the cPanel zone dump.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsRecord {
    #[serde(rename = "Line")]
    pub line: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ttl")]
    pub ttl: i32,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "cname")]
    pub cname: String,
    #[serde(rename = "exchange")]
    pub exchange: String,
    #[serde(rename = "preference")]
    pub preference: i32,
    #[serde(rename = "txtdata")]
    pub txtdata: String,
    #[serde(rename = "unencoded")]
    pub unencoded: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "weight")]
    pub weight: i32,
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "flag")]
    pub flag: i32,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl DnsRecord {
    /// Read-only representation of a DNS record from the cPanel zone dump.
    pub fn new(line: i32, name: String, ttl: i32, r#type: String, address: String, cname: String, exchange: String, preference: i32, txtdata: String, unencoded: String, target: String, priority: i32, weight: i32, port: i32, flag: i32, tag: String, value: String) -> DnsRecord {
        DnsRecord {
            line,
            name,
            ttl,
            r#type,
            address,
            cname,
            exchange,
            preference,
            txtdata,
            unencoded,
            target,
            priority,
            weight,
            port,
            flag,
            tag,
            value,
        }
    }
}

