/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainAdd {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "dns_source")]
    pub dns_source: models::DnsSourceEnum,
    #[serde(rename = "managed_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub managed_domain: Option<Option<i32>>,
    #[serde(rename = "managed_external_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub managed_external_domain: Option<Option<i32>>,
    #[serde(rename = "use_inbound", skip_serializing_if = "Option::is_none")]
    pub use_inbound: Option<bool>,
}

impl DomainAdd {
    pub fn new(name: String, dns_source: models::DnsSourceEnum) -> DomainAdd {
        DomainAdd {
            name,
            dns_source,
            managed_domain: None,
            managed_external_domain: None,
            use_inbound: None,
        }
    }
}

