/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainCreate {
    /// Domain with tld, ex: example.com
    #[serde(rename = "domain")]
    pub domain: String,
    /// List of 2-5 name-servers separated by comma.
    #[serde(rename = "nameservers", skip_serializing_if = "Option::is_none")]
    pub nameservers: Option<String>,
    #[serde(rename = "years", skip_serializing_if = "Option::is_none")]
    pub years: Option<i32>,
}

impl DomainCreate {
    pub fn new(domain: String) -> DomainCreate {
        DomainCreate {
            domain,
            nameservers: None,
            years: None,
        }
    }
}

