/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailReputation {
    #[serde(rename = "bounce_rate_pct")]
    pub bounce_rate_pct: String,
    #[serde(rename = "complaint_rate_pct")]
    pub complaint_rate_pct: String,
    #[serde(rename = "msgs_sent_24h")]
    pub msgs_sent_24h: i32,
    #[serde(rename = "msgs_sent_30d")]
    pub msgs_sent_30d: i32,
}

impl EmailReputation {
    pub fn new(bounce_rate_pct: String, complaint_rate_pct: String, msgs_sent_24h: i32, msgs_sent_30d: i32) -> EmailReputation {
        EmailReputation {
            bounce_rate_pct,
            complaint_rate_pct,
            msgs_sent_24h,
            msgs_sent_30d,
        }
    }
}

