/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EncryptionReasonCodeEnum : * `feature_unavailable` - feature_unavailable * `cluster_operation_in_progress` - cluster_operation_in_progress * `resource_not_active` - resource_not_active * `cluster_not_provisioned` - cluster_not_provisioned * `invalid_encryption_mode` - invalid_encryption_mode * `workload_restart_ack_required` - workload_restart_ack_required * `encryption_state_unknown` - encryption_state_unknown * `encryption_already_in_requested_mode` - encryption_already_in_requested_mode * `reconcile_requires_staff` - reconcile_requires_staff * `reconcile_requires_unknown_state` - reconcile_requires_unknown_state * `cilium_version_mismatch` - cilium_version_mismatch * `kernel_wireguard_unavailable` - kernel_wireguard_unavailable * `kernel_nodes_unknown` - kernel_nodes_unknown * `helm_upgrade_failed` - helm_upgrade_failed * `helm_rollback_failed` - helm_rollback_failed * `cilium_rollout_failed` - cilium_rollout_failed * `cilium_node_key_missing` - cilium_node_key_missing * `cilium_peer_verification_failed` - cilium_peer_verification_failed * `cilium_agent_unreadable` - cilium_agent_unreadable * `cilium_agent_state_mismatch` - cilium_agent_state_mismatch * `cilium_encryption_not_active` - cilium_encryption_not_active * `cilium_encryption_still_active` - cilium_encryption_still_active * `cilium_nodes_unknown` - cilium_nodes_unknown * `cilium_mode_unsupported` - cilium_mode_unsupported * `cilium_verification_misconfigured` - cilium_verification_misconfigured * `restart_recheck_failed` - restart_recheck_failed * `platform_restart_incomplete` - platform_restart_incomplete * `encryption_task_aborted` - encryption_task_aborted * `dispatch_pending` - dispatch_pending
/// * `feature_unavailable` - feature_unavailable * `cluster_operation_in_progress` - cluster_operation_in_progress * `resource_not_active` - resource_not_active * `cluster_not_provisioned` - cluster_not_provisioned * `invalid_encryption_mode` - invalid_encryption_mode * `workload_restart_ack_required` - workload_restart_ack_required * `encryption_state_unknown` - encryption_state_unknown * `encryption_already_in_requested_mode` - encryption_already_in_requested_mode * `reconcile_requires_staff` - reconcile_requires_staff * `reconcile_requires_unknown_state` - reconcile_requires_unknown_state * `cilium_version_mismatch` - cilium_version_mismatch * `kernel_wireguard_unavailable` - kernel_wireguard_unavailable * `kernel_nodes_unknown` - kernel_nodes_unknown * `helm_upgrade_failed` - helm_upgrade_failed * `helm_rollback_failed` - helm_rollback_failed * `cilium_rollout_failed` - cilium_rollout_failed * `cilium_node_key_missing` - cilium_node_key_missing * `cilium_peer_verification_failed` - cilium_peer_verification_failed * `cilium_agent_unreadable` - cilium_agent_unreadable * `cilium_agent_state_mismatch` - cilium_agent_state_mismatch * `cilium_encryption_not_active` - cilium_encryption_not_active * `cilium_encryption_still_active` - cilium_encryption_still_active * `cilium_nodes_unknown` - cilium_nodes_unknown * `cilium_mode_unsupported` - cilium_mode_unsupported * `cilium_verification_misconfigured` - cilium_verification_misconfigured * `restart_recheck_failed` - restart_recheck_failed * `platform_restart_incomplete` - platform_restart_incomplete * `encryption_task_aborted` - encryption_task_aborted * `dispatch_pending` - dispatch_pending
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncryptionReasonCodeEnum {
    #[serde(rename = "feature_unavailable")]
    FeatureUnavailable,
    #[serde(rename = "cluster_operation_in_progress")]
    ClusterOperationInProgress,
    #[serde(rename = "resource_not_active")]
    ResourceNotActive,
    #[serde(rename = "cluster_not_provisioned")]
    ClusterNotProvisioned,
    #[serde(rename = "invalid_encryption_mode")]
    InvalidEncryptionMode,
    #[serde(rename = "workload_restart_ack_required")]
    WorkloadRestartAckRequired,
    #[serde(rename = "encryption_state_unknown")]
    EncryptionStateUnknown,
    #[serde(rename = "encryption_already_in_requested_mode")]
    EncryptionAlreadyInRequestedMode,
    #[serde(rename = "reconcile_requires_staff")]
    ReconcileRequiresStaff,
    #[serde(rename = "reconcile_requires_unknown_state")]
    ReconcileRequiresUnknownState,
    #[serde(rename = "cilium_version_mismatch")]
    CiliumVersionMismatch,
    #[serde(rename = "kernel_wireguard_unavailable")]
    KernelWireguardUnavailable,
    #[serde(rename = "kernel_nodes_unknown")]
    KernelNodesUnknown,
    #[serde(rename = "helm_upgrade_failed")]
    HelmUpgradeFailed,
    #[serde(rename = "helm_rollback_failed")]
    HelmRollbackFailed,
    #[serde(rename = "cilium_rollout_failed")]
    CiliumRolloutFailed,
    #[serde(rename = "cilium_node_key_missing")]
    CiliumNodeKeyMissing,
    #[serde(rename = "cilium_peer_verification_failed")]
    CiliumPeerVerificationFailed,
    #[serde(rename = "cilium_agent_unreadable")]
    CiliumAgentUnreadable,
    #[serde(rename = "cilium_agent_state_mismatch")]
    CiliumAgentStateMismatch,
    #[serde(rename = "cilium_encryption_not_active")]
    CiliumEncryptionNotActive,
    #[serde(rename = "cilium_encryption_still_active")]
    CiliumEncryptionStillActive,
    #[serde(rename = "cilium_nodes_unknown")]
    CiliumNodesUnknown,
    #[serde(rename = "cilium_mode_unsupported")]
    CiliumModeUnsupported,
    #[serde(rename = "cilium_verification_misconfigured")]
    CiliumVerificationMisconfigured,
    #[serde(rename = "restart_recheck_failed")]
    RestartRecheckFailed,
    #[serde(rename = "platform_restart_incomplete")]
    PlatformRestartIncomplete,
    #[serde(rename = "encryption_task_aborted")]
    EncryptionTaskAborted,
    #[serde(rename = "dispatch_pending")]
    DispatchPending,

}

impl std::fmt::Display for EncryptionReasonCodeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FeatureUnavailable => write!(f, "feature_unavailable"),
            Self::ClusterOperationInProgress => write!(f, "cluster_operation_in_progress"),
            Self::ResourceNotActive => write!(f, "resource_not_active"),
            Self::ClusterNotProvisioned => write!(f, "cluster_not_provisioned"),
            Self::InvalidEncryptionMode => write!(f, "invalid_encryption_mode"),
            Self::WorkloadRestartAckRequired => write!(f, "workload_restart_ack_required"),
            Self::EncryptionStateUnknown => write!(f, "encryption_state_unknown"),
            Self::EncryptionAlreadyInRequestedMode => write!(f, "encryption_already_in_requested_mode"),
            Self::ReconcileRequiresStaff => write!(f, "reconcile_requires_staff"),
            Self::ReconcileRequiresUnknownState => write!(f, "reconcile_requires_unknown_state"),
            Self::CiliumVersionMismatch => write!(f, "cilium_version_mismatch"),
            Self::KernelWireguardUnavailable => write!(f, "kernel_wireguard_unavailable"),
            Self::KernelNodesUnknown => write!(f, "kernel_nodes_unknown"),
            Self::HelmUpgradeFailed => write!(f, "helm_upgrade_failed"),
            Self::HelmRollbackFailed => write!(f, "helm_rollback_failed"),
            Self::CiliumRolloutFailed => write!(f, "cilium_rollout_failed"),
            Self::CiliumNodeKeyMissing => write!(f, "cilium_node_key_missing"),
            Self::CiliumPeerVerificationFailed => write!(f, "cilium_peer_verification_failed"),
            Self::CiliumAgentUnreadable => write!(f, "cilium_agent_unreadable"),
            Self::CiliumAgentStateMismatch => write!(f, "cilium_agent_state_mismatch"),
            Self::CiliumEncryptionNotActive => write!(f, "cilium_encryption_not_active"),
            Self::CiliumEncryptionStillActive => write!(f, "cilium_encryption_still_active"),
            Self::CiliumNodesUnknown => write!(f, "cilium_nodes_unknown"),
            Self::CiliumModeUnsupported => write!(f, "cilium_mode_unsupported"),
            Self::CiliumVerificationMisconfigured => write!(f, "cilium_verification_misconfigured"),
            Self::RestartRecheckFailed => write!(f, "restart_recheck_failed"),
            Self::PlatformRestartIncomplete => write!(f, "platform_restart_incomplete"),
            Self::EncryptionTaskAborted => write!(f, "encryption_task_aborted"),
            Self::DispatchPending => write!(f, "dispatch_pending"),
        }
    }
}

impl Default for EncryptionReasonCodeEnum {
    fn default() -> EncryptionReasonCodeEnum {
        Self::FeatureUnavailable
    }
}

