/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeaturesEnum : * `cert-manager` - Certificate manager * `ceph-csi` - Ceph CSI * `metrics-server` - Metrics Server * `cloudnative-pg` - CloudNative PG * `mariadb-operator` - MariaDB Operator
/// * `cert-manager` - Certificate manager * `ceph-csi` - Ceph CSI * `metrics-server` - Metrics Server * `cloudnative-pg` - CloudNative PG * `mariadb-operator` - MariaDB Operator
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeaturesEnum {
    #[serde(rename = "cert-manager")]
    CertManager,
    #[serde(rename = "ceph-csi")]
    CephCsi,
    #[serde(rename = "metrics-server")]
    MetricsServer,
    #[serde(rename = "cloudnative-pg")]
    CloudnativePg,
    #[serde(rename = "mariadb-operator")]
    MariadbOperator,

}

impl std::fmt::Display for FeaturesEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CertManager => write!(f, "cert-manager"),
            Self::CephCsi => write!(f, "ceph-csi"),
            Self::MetricsServer => write!(f, "metrics-server"),
            Self::CloudnativePg => write!(f, "cloudnative-pg"),
            Self::MariadbOperator => write!(f, "mariadb-operator"),
        }
    }
}

impl Default for FeaturesEnum {
    fn default() -> FeaturesEnum {
        Self::CertManager
    }
}

