/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureUpgradeRequest {
    /// Name of the feature to upgrade (e.g. cert-manager)
    #[serde(rename = "feature_name")]
    pub feature_name: String,
    /// Retry a failed install
    #[serde(rename = "retry", skip_serializing_if = "Option::is_none")]
    pub retry: Option<bool>,
}

impl FeatureUpgradeRequest {
    pub fn new(feature_name: String) -> FeatureUpgradeRequest {
        FeatureUpgradeRequest {
            feature_name,
            retry: None,
        }
    }
}

