/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirewallRulesSet {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::FirewallRulesSetStatusEnum,
    #[serde(rename = "rules")]
    pub rules: Vec<models::FirewallRule>,
    /// used with free tier vm
    #[serde(rename = "read_only")]
    pub read_only: bool,
}

impl FirewallRulesSet {
    pub fn new(id: i32, name: String, status: models::FirewallRulesSetStatusEnum, rules: Vec<models::FirewallRule>, read_only: bool) -> FirewallRulesSet {
        FirewallRulesSet {
            id,
            name,
            status,
            rules,
            read_only,
        }
    }
}

