/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FloatingIpv4 {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "gateway")]
    pub gateway: String,
    #[serde(rename = "prefix")]
    pub prefix: i32,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "authorized_vm_count")]
    pub authorized_vm_count: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl FloatingIpv4 {
    pub fn new(id: i32, address: String, gateway: String, prefix: i32, authorized_vm_count: i32, created_at: String) -> FloatingIpv4 {
        FloatingIpv4 {
            id,
            address,
            gateway,
            prefix,
            label: None,
            authorized_vm_count,
            created_at,
        }
    }
}

