/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FloatingIpAuthorization : Read-only authorization row for either v4 or v6 (shape is identical).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FloatingIpAuthorization {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "server_id")]
    pub server_id: i32,
    #[serde(rename = "server_hostname")]
    pub server_hostname: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl FloatingIpAuthorization {
    /// Read-only authorization row for either v4 or v6 (shape is identical).
    pub fn new(id: i32, server_id: i32, server_hostname: String, created_at: String) -> FloatingIpAuthorization {
        FloatingIpAuthorization {
            id,
            server_id,
            server_hostname,
            created_at,
        }
    }
}

