/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HttpRoute : Serializer for HTTPRoute resources with automatic certificate issuance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpRoute {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// List of hostnames to route (e.g., [\"example.com\", \"www.example.com\"])
    #[serde(rename = "hostnames")]
    pub hostnames: Vec<String>,
    /// Name of the backend Kubernetes Service
    #[serde(rename = "backend_service_name")]
    pub backend_service_name: String,
    /// Port of the backend Service
    #[serde(rename = "backend_service_port")]
    pub backend_service_port: i32,
    /// Namespace of the backend Service
    #[serde(rename = "backend_namespace", skip_serializing_if = "Option::is_none")]
    pub backend_namespace: Option<String>,
    /// Path prefix to match (default: /)
    #[serde(rename = "path_prefix", skip_serializing_if = "Option::is_none")]
    pub path_prefix: Option<String>,
    /// Enable TLS termination with automatic certificate issuance
    #[serde(rename = "enable_tls", skip_serializing_if = "Option::is_none")]
    pub enable_tls: Option<bool>,
    #[serde(rename = "status_ready", deserialize_with = "Option::deserialize")]
    pub status_ready: Option<bool>,
    #[serde(rename = "status_message")]
    pub status_message: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "updated")]
    pub updated: String,
}

impl HttpRoute {
    /// Serializer for HTTPRoute resources with automatic certificate issuance.
    pub fn new(id: i32, name: String, hostnames: Vec<String>, backend_service_name: String, backend_service_port: i32, status_ready: Option<bool>, status_message: String, created: String, updated: String) -> HttpRoute {
        HttpRoute {
            id,
            name,
            namespace: None,
            hostnames,
            backend_service_name,
            backend_service_port,
            backend_namespace: None,
            path_prefix: None,
            enable_tls: None,
            status_ready,
            status_message,
            created,
            updated,
        }
    }
}

