/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundRoute {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "domain")]
    pub domain: i32,
    #[serde(rename = "pattern")]
    pub pattern: String,
    #[serde(rename = "mode")]
    pub mode: models::ModeEnum,
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
    #[serde(rename = "forward_to", skip_serializing_if = "Option::is_none")]
    pub forward_to: Option<String>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl InboundRoute {
    pub fn new(id: i32, domain: i32, pattern: String, mode: models::ModeEnum, created_at: String) -> InboundRoute {
        InboundRoute {
            id,
            domain,
            pattern,
            mode,
            webhook_url: None,
            forward_to: None,
            active: None,
            created_at,
        }
    }
}

