/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceList {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "number_proforma")]
    pub number_proforma: String,
    #[serde(rename = "number_fiscal")]
    pub number_fiscal: String,
    #[serde(rename = "status")]
    pub status: models::InvoiceStatusEnum,
    #[serde(rename = "subtotal")]
    pub subtotal: String,
    #[serde(rename = "vat_value")]
    pub vat_value: String,
    #[serde(rename = "vat_percentage")]
    pub vat_percentage: i32,
    #[serde(rename = "total")]
    pub total: String,
    #[serde(rename = "invoice_date")]
    pub invoice_date: chrono::NaiveDate,
    #[serde(rename = "due_date", deserialize_with = "Option::deserialize")]
    pub due_date: Option<chrono::NaiveDate>,
    #[serde(rename = "payment_date", deserialize_with = "Option::deserialize")]
    pub payment_date: Option<String>,
}

impl InvoiceList {
    pub fn new(id: i32, number_proforma: String, number_fiscal: String, status: models::InvoiceStatusEnum, subtotal: String, vat_value: String, vat_percentage: i32, total: String, invoice_date: chrono::NaiveDate, due_date: Option<chrono::NaiveDate>, payment_date: Option<String>) -> InvoiceList {
        InvoiceList {
            id,
            number_proforma,
            number_fiscal,
            status,
            subtotal,
            vat_value,
            vat_percentage,
            total,
            invoice_date,
            due_date,
            payment_date,
        }
    }
}

