/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LbFirewallRule {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<models::LbFirewallRuleDirectionEnum>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::LbFirewallRuleActionEnum>,
    /// tcp, udp, icmp, etc.
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// IP address or CIDR
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Port or range (e.g., 1024-65535)
    #[serde(rename = "sport", skip_serializing_if = "Option::is_none")]
    pub sport: Option<String>,
    /// IP address or CIDR
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    /// Port or range (e.g., 80, 8000-9000)
    #[serde(rename = "dport", skip_serializing_if = "Option::is_none")]
    pub dport: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Rule order (lower = higher priority)
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "updated")]
    pub updated: String,
}

impl LbFirewallRule {
    pub fn new(id: i32, created: String, updated: String) -> LbFirewallRule {
        LbFirewallRule {
            id,
            direction: None,
            action: None,
            protocol: None,
            source: None,
            sport: None,
            destination: None,
            dport: None,
            comment: None,
            enabled: None,
            position: None,
            created,
            updated,
        }
    }
}

