/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeMetricsResponse {
    #[serde(rename = "cpu")]
    pub cpu: f64,
    #[serde(rename = "mem")]
    pub mem: i32,
    #[serde(rename = "maxmem")]
    pub maxmem: i32,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "uptime")]
    pub uptime: i32,
    #[serde(rename = "netin")]
    pub netin: i32,
    #[serde(rename = "netout")]
    pub netout: i32,
}

impl NodeMetricsResponse {
    pub fn new(cpu: f64, mem: i32, maxmem: i32, status: String, uptime: i32, netin: i32, netout: i32) -> NodeMetricsResponse {
        NodeMetricsResponse {
            cpu,
            mem,
            maxmem,
            status,
            uptime,
            netin,
            netout,
        }
    }
}

