/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodeOperationRebootRequest : A reboot destroys the same local data a delete does, and says so.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeOperationRebootRequest {
    /// Acknowledge that data kept on the node itself is destroyed. The drain always deletes emptyDir.
    #[serde(rename = "local_data_loss_accepted", skip_serializing_if = "Option::is_none")]
    pub local_data_loss_accepted: Option<bool>,
}

impl NodeOperationRebootRequest {
    /// A reboot destroys the same local data a delete does, and says so.
    pub fn new() -> NodeOperationRebootRequest {
        NodeOperationRebootRequest {
            local_data_loss_accepted: None,
        }
    }
}

