/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodeOperation : What a customer may see about their own node operation.  The omissions are the point. Private address, Node UID, VMID, Proxmox placement, and every request/task/lease field stay on the staff serializer: they name internal topology, and a status endpoint is not where that becomes public.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeOperation {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "kind")]
    pub kind: models::NodeOperationKindEnum,
    #[serde(rename = "source")]
    pub source: models::NodeOperationSourceEnum,
    #[serde(rename = "target_hostname")]
    pub target_hostname: String,
    #[serde(rename = "status")]
    pub status: models::NodeOperationStatusEnum,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "bypass_pdb")]
    pub bypass_pdb: bool,
    #[serde(rename = "delete_unmanaged_pods")]
    pub delete_unmanaged_pods: bool,
    #[serde(rename = "local_data_loss_accepted")]
    pub local_data_loss_accepted: bool,
    #[serde(rename = "bypass_pdb_confirmed_at", deserialize_with = "Option::deserialize")]
    pub bypass_pdb_confirmed_at: Option<String>,
    #[serde(rename = "unmanaged_pods_confirmed_at", deserialize_with = "Option::deserialize")]
    pub unmanaged_pods_confirmed_at: Option<String>,
    /// Who requested the operation (user email or staff name). Never token material.
    #[serde(rename = "actor_label")]
    pub actor_label: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "finished_at", deserialize_with = "Option::deserialize")]
    pub finished_at: Option<String>,
    #[serde(rename = "allowed_actions")]
    pub allowed_actions: Vec<String>,
}

impl NodeOperation {
    /// What a customer may see about their own node operation.  The omissions are the point. Private address, Node UID, VMID, Proxmox placement, and every request/task/lease field stay on the staff serializer: they name internal topology, and a status endpoint is not where that becomes public.
    pub fn new(id: i32, kind: models::NodeOperationKindEnum, source: models::NodeOperationSourceEnum, target_hostname: String, status: models::NodeOperationStatusEnum, reason: String, message: String, bypass_pdb: bool, delete_unmanaged_pods: bool, local_data_loss_accepted: bool, bypass_pdb_confirmed_at: Option<String>, unmanaged_pods_confirmed_at: Option<String>, actor_label: String, created_at: String, updated_at: String, finished_at: Option<String>, allowed_actions: Vec<String>) -> NodeOperation {
        NodeOperation {
            id,
            kind,
            source,
            target_hostname,
            status,
            reason,
            message,
            bypass_pdb,
            delete_unmanaged_pods,
            local_data_loss_accepted,
            bypass_pdb_confirmed_at,
            unmanaged_pods_confirmed_at,
            actor_label,
            created_at,
            updated_at,
            finished_at,
            allowed_actions,
        }
    }
}

