/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSettingsResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "threshold_type")]
    pub threshold_type: String,
    #[serde(rename = "threshold_amount", deserialize_with = "Option::deserialize")]
    pub threshold_amount: Option<String>,
    #[serde(rename = "threshold_days", deserialize_with = "Option::deserialize")]
    pub threshold_days: Option<i32>,
}

impl NotificationSettingsResponse {
    pub fn new(message: String, threshold_type: String, threshold_amount: Option<String>, threshold_days: Option<i32>) -> NotificationSettingsResponse {
        NotificationSettingsResponse {
            message,
            threshold_type,
            threshold_amount,
            threshold_days,
        }
    }
}

