/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OperationEnum : * `added` - Added funds * `used` - Used funds for payment * `refunded` - Refunded funds * `recalculated` - Funds adjustment * `used_for_apps` - Used funds for Apps * `used_for_cloud` - Used funds for cloud services * `used_for_cloud_provision` - Used funds for cloud provision * `downgrade_credit` - Downgrade credit * `referral_reward` - Referral reward * `used_for_wishlist` - Used funds for domain wishlist
/// * `added` - Added funds * `used` - Used funds for payment * `refunded` - Refunded funds * `recalculated` - Funds adjustment * `used_for_apps` - Used funds for Apps * `used_for_cloud` - Used funds for cloud services * `used_for_cloud_provision` - Used funds for cloud provision * `downgrade_credit` - Downgrade credit * `referral_reward` - Referral reward * `used_for_wishlist` - Used funds for domain wishlist
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperationEnum {
    #[serde(rename = "added")]
    Added,
    #[serde(rename = "used")]
    Used,
    #[serde(rename = "refunded")]
    Refunded,
    #[serde(rename = "recalculated")]
    Recalculated,
    #[serde(rename = "used_for_apps")]
    UsedForApps,
    #[serde(rename = "used_for_cloud")]
    UsedForCloud,
    #[serde(rename = "used_for_cloud_provision")]
    UsedForCloudProvision,
    #[serde(rename = "downgrade_credit")]
    DowngradeCredit,
    #[serde(rename = "referral_reward")]
    ReferralReward,
    #[serde(rename = "used_for_wishlist")]
    UsedForWishlist,

}

impl std::fmt::Display for OperationEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Added => write!(f, "added"),
            Self::Used => write!(f, "used"),
            Self::Refunded => write!(f, "refunded"),
            Self::Recalculated => write!(f, "recalculated"),
            Self::UsedForApps => write!(f, "used_for_apps"),
            Self::UsedForCloud => write!(f, "used_for_cloud"),
            Self::UsedForCloudProvision => write!(f, "used_for_cloud_provision"),
            Self::DowngradeCredit => write!(f, "downgrade_credit"),
            Self::ReferralReward => write!(f, "referral_reward"),
            Self::UsedForWishlist => write!(f, "used_for_wishlist"),
        }
    }
}

impl Default for OperationEnum {
    fn default() -> OperationEnum {
        Self::Added
    }
}

