/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OsImage {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "slug")]
    pub slug: String,
    /// Display name for users
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "family_name")]
    pub family_name: String,
    /// Default version within this family (shown pre-selected)
    #[serde(rename = "is_default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
}

impl OsImage {
    pub fn new(id: i32, slug: String, name: String, family_name: String) -> OsImage {
        OsImage {
            id,
            slug,
            name,
            family_name,
            is_default: None,
        }
    }
}

