/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedServerDetail {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "package", skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,
    #[serde(rename = "cpus", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<i32>,
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
    #[serde(rename = "disk_size", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<i32>,
    #[serde(rename = "machine", skip_serializing_if = "Option::is_none")]
    pub machine: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "volumes", skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<models::Volume>>,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::StatusA57Enum>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Prevents the server from being destroyed until disabled.
    #[serde(rename = "destroy_protection", skip_serializing_if = "Option::is_none")]
    pub destroy_protection: Option<bool>,
    /// Enables Proxmox HA — automatic restart and migration on node failure.
    #[serde(rename = "ha_enabled", skip_serializing_if = "Option::is_none")]
    pub ha_enabled: Option<bool>,
}

impl PatchedServerDetail {
    pub fn new() -> PatchedServerDetail {
        PatchedServerDetail {
            id: None,
            hostname: None,
            project: None,
            image: None,
            package: None,
            cpus: None,
            memory: None,
            disk_size: None,
            machine: None,
            volumes: None,
            networks: None,
            password: None,
            status: None,
            username: None,
            destroy_protection: None,
            ha_enabled: None,
        }
    }
}

