/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedPrivateNetwork {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// CIDR format
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// CIDR format
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "gateway", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gateway: Option<Option<String>>,
    #[serde(rename = "provisioned", skip_serializing_if = "Option::is_none")]
    pub provisioned: Option<bool>,
    #[serde(rename = "servers", skip_serializing_if = "Option::is_none")]
    pub servers: Option<Vec<std::collections::HashMap<String, String>>>,
}

impl PatchedPrivateNetwork {
    pub fn new() -> PatchedPrivateNetwork {
        PatchedPrivateNetwork {
            id: None,
            slug: None,
            address: None,
            gateway: None,
            provisioned: None,
            servers: None,
        }
    }
}

