/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedServerDetail {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "package", skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,
    #[serde(rename = "cpus", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<i32>,
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i32>,
    #[serde(rename = "disk_size", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<i32>,
    #[serde(rename = "generation", skip_serializing_if = "Option::is_none")]
    pub generation: Option<String>,
    #[serde(rename = "machine", skip_serializing_if = "Option::is_none")]
    pub machine: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "volumes", skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<models::Volume>>,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "floating_ips", skip_serializing_if = "Option::is_none")]
    pub floating_ips: Option<Vec<models::FloatingIpSummary>>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Public key to apply for SSH login. Applying a non-empty key regenerates cloud-init and reboots a running server. Clearing removes the key from future cloud-init data, but does not revoke keys already in the guest.
    #[serde(rename = "ssh_pub_key", skip_serializing_if = "Option::is_none")]
    pub ssh_pub_key: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ResourceStatusEnum>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Prevents the server from being destroyed until disabled.
    #[serde(rename = "destroy_protection", skip_serializing_if = "Option::is_none")]
    pub destroy_protection: Option<bool>,
    /// Enables Proxmox HA — automatic restart and migration on node failure.
    #[serde(rename = "ha_enabled", skip_serializing_if = "Option::is_none")]
    pub ha_enabled: Option<bool>,
    /// Customer installed their own OS from an ISO; cloud-init features no longer apply
    #[serde(rename = "custom_os", skip_serializing_if = "Option::is_none")]
    pub custom_os: Option<bool>,
    #[serde(rename = "rescue_mode", skip_serializing_if = "Option::is_none")]
    pub rescue_mode: Option<bool>,
    #[serde(rename = "boot_iso", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub boot_iso: Option<Option<String>>,
    #[serde(rename = "rescue_supported", skip_serializing_if = "Option::is_none")]
    pub rescue_supported: Option<bool>,
}

impl PatchedServerDetail {
    pub fn new() -> PatchedServerDetail {
        PatchedServerDetail {
            id: None,
            hostname: None,
            project: None,
            image: None,
            package: None,
            cpus: None,
            memory: None,
            disk_size: None,
            generation: None,
            machine: None,
            volumes: None,
            networks: None,
            floating_ips: None,
            password: None,
            ssh_pub_key: None,
            status: None,
            username: None,
            destroy_protection: None,
            ha_enabled: None,
            custom_os: None,
            rescue_mode: None,
            boot_iso: None,
            rescue_supported: None,
        }
    }
}

