/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedEmailService {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::StatusA57Enum>,
    #[serde(rename = "sandbox_mode", skip_serializing_if = "Option::is_none")]
    pub sandbox_mode: Option<bool>,
    #[serde(rename = "auto_suspended", skip_serializing_if = "Option::is_none")]
    pub auto_suspended: Option<bool>,
    #[serde(rename = "auto_suspend_reason", skip_serializing_if = "Option::is_none")]
    pub auto_suspend_reason: Option<String>,
    #[serde(rename = "msgs_sent_24h", skip_serializing_if = "Option::is_none")]
    pub msgs_sent_24h: Option<i32>,
    #[serde(rename = "msgs_sent_30d", skip_serializing_if = "Option::is_none")]
    pub msgs_sent_30d: Option<i32>,
    #[serde(rename = "bounce_rate_pct", skip_serializing_if = "Option::is_none")]
    pub bounce_rate_pct: Option<String>,
    #[serde(rename = "complaint_rate_pct", skip_serializing_if = "Option::is_none")]
    pub complaint_rate_pct: Option<String>,
    #[serde(rename = "dedicated_ip_addon", skip_serializing_if = "Option::is_none")]
    pub dedicated_ip_addon: Option<bool>,
    #[serde(rename = "quota_monthly", skip_serializing_if = "Option::is_none")]
    pub quota_monthly: Option<String>,
    #[serde(rename = "price_monthly_eur", skip_serializing_if = "Option::is_none")]
    pub price_monthly_eur: Option<String>,
}

impl PatchedEmailService {
    pub fn new() -> PatchedEmailService {
        PatchedEmailService {
            id: None,
            tier: None,
            status: None,
            sandbox_mode: None,
            auto_suspended: None,
            auto_suspend_reason: None,
            msgs_sent_24h: None,
            msgs_sent_30d: None,
            bounce_rate_pct: None,
            complaint_rate_pct: None,
            dedicated_ip_addon: None,
            quota_monthly: None,
            price_monthly_eur: None,
        }
    }
}

