/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedDomain {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "tld", skip_serializing_if = "Option::is_none")]
    pub tld: Option<Box<models::Tld>>,
    /// Domain name is encoded with IDN
    #[serde(rename = "idna", skip_serializing_if = "Option::is_none")]
    pub idna: Option<bool>,
    /// List of 2-5 name-servers separated by comma.
    #[serde(rename = "nameservers", skip_serializing_if = "Option::is_none")]
    pub nameservers: Option<String>,
    #[serde(rename = "expiration_date", skip_serializing_if = "Option::is_none")]
    pub expiration_date: Option<String>,
    #[serde(rename = "registration_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub registration_date: Option<Option<String>>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<Box<models::Service>>,
    #[serde(rename = "idna_name", skip_serializing_if = "Option::is_none")]
    pub idna_name: Option<String>,
    #[serde(rename = "max_renew_years", skip_serializing_if = "Option::is_none")]
    pub max_renew_years: Option<i32>,
    /// Service status
    #[serde(rename = "service_status", skip_serializing_if = "Option::is_none")]
    pub service_status: Option<String>,
    #[serde(rename = "contacts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contacts: Option<Option<serde_json::Value>>,
}

impl PatchedDomain {
    pub fn new() -> PatchedDomain {
        PatchedDomain {
            id: None,
            domain: None,
            tld: None,
            idna: None,
            nameservers: None,
            expiration_date: None,
            registration_date: None,
            service: None,
            idna_name: None,
            max_renew_years: None,
            service_status: None,
            contacts: None,
        }
    }
}

