/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PoolRemovalJournalStatusEnum : * `pending` - Pending * `preflight` - Preflight * `destructive` - Destructive phase * `needs_attention` - Needs attention * `failed` - Failed * `succeeded` - Succeeded
/// * `pending` - Pending * `preflight` - Preflight * `destructive` - Destructive phase * `needs_attention` - Needs attention * `failed` - Failed * `succeeded` - Succeeded
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PoolRemovalJournalStatusEnum {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "preflight")]
    Preflight,
    #[serde(rename = "destructive")]
    Destructive,
    #[serde(rename = "needs_attention")]
    NeedsAttention,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "succeeded")]
    Succeeded,

}

impl std::fmt::Display for PoolRemovalJournalStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "pending"),
            Self::Preflight => write!(f, "preflight"),
            Self::Destructive => write!(f, "destructive"),
            Self::NeedsAttention => write!(f, "needs_attention"),
            Self::Failed => write!(f, "failed"),
            Self::Succeeded => write!(f, "succeeded"),
        }
    }
}

impl Default for PoolRemovalJournalStatusEnum {
    fn default() -> PoolRemovalJournalStatusEnum {
        Self::Pending
    }
}

