/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PoolRemovalItem : One worker a journal is removing, and how far its removal got.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoolRemovalItem {
    #[serde(rename = "target_hostname")]
    pub target_hostname: String,
    #[serde(rename = "cordoned_at", deserialize_with = "Option::deserialize")]
    pub cordoned_at: Option<String>,
    #[serde(rename = "drained_at", deserialize_with = "Option::deserialize")]
    pub drained_at: Option<String>,
    #[serde(rename = "detached_at", deserialize_with = "Option::deserialize")]
    pub detached_at: Option<String>,
    #[serde(rename = "validated_at", deserialize_with = "Option::deserialize")]
    pub validated_at: Option<String>,
    #[serde(rename = "reset_started_at", deserialize_with = "Option::deserialize")]
    pub reset_started_at: Option<String>,
    #[serde(rename = "reset_completed_at", deserialize_with = "Option::deserialize")]
    pub reset_completed_at: Option<String>,
    #[serde(rename = "node_deleted_at", deserialize_with = "Option::deserialize")]
    pub node_deleted_at: Option<String>,
    #[serde(rename = "vm_deleted_at", deserialize_with = "Option::deserialize")]
    pub vm_deleted_at: Option<String>,
    #[serde(rename = "uncordoned_at", deserialize_with = "Option::deserialize")]
    pub uncordoned_at: Option<String>,
}

impl PoolRemovalItem {
    /// One worker a journal is removing, and how far its removal got.
    pub fn new(target_hostname: String, cordoned_at: Option<String>, drained_at: Option<String>, detached_at: Option<String>, validated_at: Option<String>, reset_started_at: Option<String>, reset_completed_at: Option<String>, node_deleted_at: Option<String>, vm_deleted_at: Option<String>, uncordoned_at: Option<String>) -> PoolRemovalItem {
        PoolRemovalItem {
            target_hostname,
            cordoned_at,
            drained_at,
            detached_at,
            validated_at,
            reset_started_at,
            reset_completed_at,
            node_deleted_at,
            vm_deleted_at,
            uncordoned_at,
        }
    }
}

