/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicIpv4 {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "gateway")]
    pub gateway: String,
    #[serde(rename = "prefix")]
    pub prefix: i32,
    #[serde(rename = "attached")]
    pub attached: bool,
    /// Hostname of the server this address is attached to. Empty when it is not attached.
    #[serde(rename = "server")]
    pub server: String,
    /// ID of the attached server, as used by /api/cloud/servers/{id}/. Null when the address is not attached to a cloud server.
    #[serde(rename = "server_id", deserialize_with = "Option::deserialize")]
    pub server_id: Option<i32>,
}

impl PublicIpv4 {
    pub fn new(id: i32, slug: String, address: String, gateway: String, prefix: i32, attached: bool, server: String, server_id: Option<i32>) -> PublicIpv4 {
        PublicIpv4 {
            id,
            slug,
            address,
            gateway,
            prefix,
            attached,
            server,
            server_id,
        }
    }
}

