/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendRequest {
    #[serde(rename = "from_address")]
    pub from_address: String,
    #[serde(rename = "to")]
    pub to: Vec<String>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<String>>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<String>>,
    #[serde(rename = "reply_to", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html_body", skip_serializing_if = "Option::is_none")]
    pub html_body: Option<String>,
    #[serde(rename = "plain_body", skip_serializing_if = "Option::is_none")]
    pub plain_body: Option<String>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "track_opens", skip_serializing_if = "Option::is_none")]
    pub track_opens: Option<bool>,
    #[serde(rename = "track_clicks", skip_serializing_if = "Option::is_none")]
    pub track_clicks: Option<bool>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::AttachmentRequest>>,
}

impl SendRequest {
    pub fn new(from_address: String, to: Vec<String>, subject: String) -> SendRequest {
        SendRequest {
            from_address,
            to,
            cc: None,
            bcc: None,
            reply_to: None,
            subject,
            html_body: None,
            plain_body: None,
            headers: None,
            track_opens: None,
            track_clicks: None,
            attachments: None,
        }
    }
}

