/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendingDomain {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: models::SendingDomainStatusEnum,
    #[serde(rename = "dns_source")]
    pub dns_source: models::DnsSourceEnum,
    #[serde(rename = "use_inbound")]
    pub use_inbound: bool,
    #[serde(rename = "dkim_selector")]
    pub dkim_selector: String,
    #[serde(rename = "dkim_record")]
    pub dkim_record: String,
    #[serde(rename = "spf_record")]
    pub spf_record: String,
    #[serde(rename = "dmarc_record")]
    pub dmarc_record: String,
    #[serde(rename = "verified_at", deserialize_with = "Option::deserialize")]
    pub verified_at: Option<String>,
    #[serde(rename = "last_check_at", deserialize_with = "Option::deserialize")]
    pub last_check_at: Option<String>,
    #[serde(rename = "last_check_errors", deserialize_with = "Option::deserialize")]
    pub last_check_errors: Option<serde_json::Value>,
}

impl SendingDomain {
    pub fn new(id: i32, name: String, status: models::SendingDomainStatusEnum, dns_source: models::DnsSourceEnum, use_inbound: bool, dkim_selector: String, dkim_record: String, spf_record: String, dmarc_record: String, verified_at: Option<String>, last_check_at: Option<String>, last_check_errors: Option<serde_json::Value>) -> SendingDomain {
        SendingDomain {
            id,
            name,
            status,
            dns_source,
            use_inbound,
            dkim_selector,
            dkim_record,
            spf_record,
            dmarc_record,
            verified_at,
            last_check_at,
            last_check_errors,
        }
    }
}

