/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerAdd {
    /// ID or slug
    #[serde(rename = "image")]
    pub image: String,
    /// ID or slug
    #[serde(rename = "package")]
    pub package: String,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// New SSH key
    #[serde(rename = "ssh_pub_key", skip_serializing_if = "Option::is_none")]
    pub ssh_pub_key: Option<String>,
    /// ID or fingerprint
    #[serde(rename = "ssh_pub_key_id", skip_serializing_if = "Option::is_none")]
    pub ssh_pub_key_id: Option<String>,
    /// ID or slug
    #[serde(rename = "public_ip", skip_serializing_if = "Option::is_none")]
    pub public_ip: Option<String>,
    #[serde(rename = "new_ipv4", skip_serializing_if = "Option::is_none")]
    pub new_ipv4: Option<bool>,
    /// ID or slug
    #[serde(rename = "public_ipv6", skip_serializing_if = "Option::is_none")]
    pub public_ipv6: Option<String>,
    #[serde(rename = "new_ipv6", skip_serializing_if = "Option::is_none")]
    pub new_ipv6: Option<bool>,
    /// ID or slug
    #[serde(rename = "fw_rules_set", skip_serializing_if = "Option::is_none")]
    pub fw_rules_set: Option<String>,
    #[serde(rename = "fw_policy_in", skip_serializing_if = "Option::is_none")]
    pub fw_policy_in: Option<models::FwPolicyOutEnum>,
    #[serde(rename = "fw_policy_out", skip_serializing_if = "Option::is_none")]
    pub fw_policy_out: Option<models::FwPolicyOutEnum>,
    /// ID or slug
    #[serde(rename = "private_network", skip_serializing_if = "Option::is_none")]
    pub private_network: Option<String>,
    /// Leave empty for auto-assign
    #[serde(rename = "private_address", skip_serializing_if = "Option::is_none")]
    pub private_address: Option<String>,
    /// ID or slug
    #[serde(rename = "extra_volume_product", skip_serializing_if = "Option::is_none")]
    pub extra_volume_product: Option<String>,
    #[serde(rename = "extra_volume_size", skip_serializing_if = "Option::is_none")]
    pub extra_volume_size: Option<i32>,
    #[serde(rename = "no_network_acknowledged", skip_serializing_if = "Option::is_none")]
    pub no_network_acknowledged: Option<bool>,
    #[serde(rename = "enable_ha", skip_serializing_if = "Option::is_none")]
    pub enable_ha: Option<bool>,
}

impl ServerAdd {
    pub fn new(image: String, package: String) -> ServerAdd {
        ServerAdd {
            image,
            package,
            hostname: None,
            project: None,
            password: None,
            ssh_pub_key: None,
            ssh_pub_key_id: None,
            public_ip: None,
            new_ipv4: None,
            public_ipv6: None,
            new_ipv6: None,
            fw_rules_set: None,
            fw_policy_in: None,
            fw_policy_out: None,
            private_network: None,
            private_address: None,
            extra_volume_product: None,
            extra_volume_size: None,
            no_network_acknowledged: None,
            enable_ha: None,
        }
    }
}

