/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Server {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "image")]
    pub image: String,
    #[serde(rename = "package")]
    pub package: String,
    #[serde(rename = "cpus")]
    pub cpus: i32,
    #[serde(rename = "memory")]
    pub memory: i32,
    #[serde(rename = "disk_size")]
    pub disk_size: i32,
    #[serde(rename = "generation")]
    pub generation: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ResourceStatusEnum>,
    /// Prevents the server from being destroyed until disabled.
    #[serde(rename = "destroy_protection")]
    pub destroy_protection: bool,
    /// Enables Proxmox HA — automatic restart and migration on node failure.
    #[serde(rename = "ha_enabled")]
    pub ha_enabled: bool,
    /// Customer installed their own OS from an ISO; cloud-init features no longer apply
    #[serde(rename = "custom_os")]
    pub custom_os: bool,
    #[serde(rename = "networks")]
    pub networks: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "rescue_mode")]
    pub rescue_mode: bool,
    #[serde(rename = "boot_iso", deserialize_with = "Option::deserialize")]
    pub boot_iso: Option<String>,
    #[serde(rename = "rescue_supported")]
    pub rescue_supported: bool,
}

impl Server {
    pub fn new(id: i32, image: String, package: String, cpus: i32, memory: i32, disk_size: i32, generation: String, destroy_protection: bool, ha_enabled: bool, custom_os: bool, networks: std::collections::HashMap<String, serde_json::Value>, rescue_mode: bool, boot_iso: Option<String>, rescue_supported: bool) -> Server {
        Server {
            id,
            hostname: None,
            project: None,
            image,
            package,
            cpus,
            memory,
            disk_size,
            generation,
            status: None,
            destroy_protection,
            ha_enabled,
            custom_os,
            networks,
            rescue_mode,
            boot_iso,
            rescue_supported,
        }
    }
}

