/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceList {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "hostname")]
    pub hostname: String,
    #[serde(rename = "status")]
    pub status: models::Status63aEnum,
    /// Euro without TVA
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "next_invoice")]
    pub next_invoice: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "billing_cycle")]
    pub billing_cycle: String,
    #[serde(rename = "auto_payment")]
    pub auto_payment: String,
    #[serde(rename = "company")]
    pub company: String,
}

impl ServiceList {
    pub fn new(id: i32, hostname: String, status: models::Status63aEnum, price: String, next_invoice: String, created: String, billing_cycle: String, auto_payment: String, company: String) -> ServiceList {
        ServiceList {
            id,
            hostname,
            status,
            price,
            next_invoice,
            created,
            billing_cycle,
            auto_payment,
            company,
        }
    }
}

