/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerProduct {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "cpus")]
    pub cpus: i32,
    #[serde(rename = "memory")]
    pub memory: i32,
    #[serde(rename = "disk_size")]
    pub disk_size: i32,
    #[serde(rename = "traffic")]
    pub traffic: i32,
    #[serde(rename = "available_generations")]
    pub available_generations: Vec<String>,
}

impl ServerProduct {
    pub fn new(id: i32, slug: String, name: String, cpus: i32, memory: i32, disk_size: i32, traffic: i32, available_generations: Vec<String>) -> ServerProduct {
        ServerProduct {
            id,
            slug,
            name,
            cpus,
            memory,
            disk_size,
            traffic,
            available_generations,
        }
    }
}

