/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Service {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "company", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub company: Option<Option<i32>>,
    #[serde(rename = "billing_cycle")]
    pub billing_cycle: i32,
    #[serde(rename = "hostname")]
    pub hostname: String,
    /// Euro without TVA
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "status")]
    pub status: models::ServiceStatusEnum,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "modified")]
    pub modified: String,
    #[serde(rename = "terminated", deserialize_with = "Option::deserialize")]
    pub terminated: Option<chrono::NaiveDate>,
    #[serde(rename = "next_invoice")]
    pub next_invoice: chrono::NaiveDate,
    #[serde(rename = "primary_service", deserialize_with = "Option::deserialize")]
    pub primary_service: Option<i32>,
}

impl Service {
    pub fn new(id: i32, billing_cycle: i32, hostname: String, price: String, status: models::ServiceStatusEnum, created: String, modified: String, terminated: Option<chrono::NaiveDate>, next_invoice: chrono::NaiveDate, primary_service: Option<i32>) -> Service {
        Service {
            id,
            company: None,
            billing_cycle,
            hostname,
            price,
            status,
            created,
            modified,
            terminated,
            next_invoice,
            primary_service,
        }
    }
}

