/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsDay {
    #[serde(rename = "sent")]
    pub sent: i32,
    #[serde(rename = "delivered")]
    pub delivered: i32,
    #[serde(rename = "hard_bounce")]
    pub hard_bounce: i32,
    #[serde(rename = "soft_bounce")]
    pub soft_bounce: i32,
    #[serde(rename = "complaint")]
    pub complaint: i32,
    #[serde(rename = "opened")]
    pub opened: i32,
    #[serde(rename = "clicked")]
    pub clicked: i32,
    #[serde(rename = "rejected")]
    pub rejected: i32,
    #[serde(rename = "day")]
    pub day: chrono::NaiveDate,
}

impl StatsDay {
    pub fn new(sent: i32, delivered: i32, hard_bounce: i32, soft_bounce: i32, complaint: i32, opened: i32, clicked: i32, rejected: i32, day: chrono::NaiveDate) -> StatsDay {
        StatsDay {
            sent,
            delivered,
            hard_bounce,
            soft_bounce,
            complaint,
            opened,
            clicked,
            rejected,
            day,
        }
    }
}

