/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Status03cEnum : * `unpaid` - Unpaid * `paid` - Paid * `paid_with_funds` - Paid with funds * `overdue` - Overdue * `processing` - Processing * `cancelled` - Cancelled * `refunded` - Refunded
/// * `unpaid` - Unpaid * `paid` - Paid * `paid_with_funds` - Paid with funds * `overdue` - Overdue * `processing` - Processing * `cancelled` - Cancelled * `refunded` - Refunded
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status03cEnum {
    #[serde(rename = "unpaid")]
    Unpaid,
    #[serde(rename = "paid")]
    Paid,
    #[serde(rename = "paid_with_funds")]
    PaidWithFunds,
    #[serde(rename = "overdue")]
    Overdue,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "refunded")]
    Refunded,

}

impl std::fmt::Display for Status03cEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unpaid => write!(f, "unpaid"),
            Self::Paid => write!(f, "paid"),
            Self::PaidWithFunds => write!(f, "paid_with_funds"),
            Self::Overdue => write!(f, "overdue"),
            Self::Processing => write!(f, "processing"),
            Self::Cancelled => write!(f, "cancelled"),
            Self::Refunded => write!(f, "refunded"),
        }
    }
}

impl Default for Status03cEnum {
    fn default() -> Status03cEnum {
        Self::Unpaid
    }
}

