/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusEf2Enum : * `new` - New * `answered` - Staff answered * `reply` - Customer replied * `closed` - Closed
/// * `new` - New * `answered` - Staff answered * `reply` - Customer replied * `closed` - Closed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEf2Enum {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "answered")]
    Answered,
    #[serde(rename = "reply")]
    Reply,
    #[serde(rename = "closed")]
    Closed,

}

impl std::fmt::Display for StatusEf2Enum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "new"),
            Self::Answered => write!(f, "answered"),
            Self::Reply => write!(f, "reply"),
            Self::Closed => write!(f, "closed"),
        }
    }
}

impl Default for StatusEf2Enum {
    fn default() -> StatusEf2Enum {
        Self::New
    }
}

