/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageProduct {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "unit")]
    pub unit: String,
    /// price per quantity units per month (if applicable)
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "min_size")]
    pub min_size: String,
    #[serde(rename = "max_size")]
    pub max_size: String,
}

impl StorageProduct {
    pub fn new(id: i32, slug: String, name: String, r#type: String, unit: String, price: String, min_size: String, max_size: String) -> StorageProduct {
        StorageProduct {
            id,
            slug,
            name,
            r#type,
            unit,
            price,
            min_size,
            max_size,
        }
    }
}

