/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscription {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "status")]
    pub status: models::SubscriptionStatusEnum,
    #[serde(rename = "service")]
    pub service: i32,
    #[serde(rename = "service_hostname")]
    pub service_hostname: String,
    #[serde(rename = "subtotal")]
    pub subtotal: String,
    #[serde(rename = "vat_value")]
    pub vat_value: String,
    #[serde(rename = "total")]
    pub total: String,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
}

impl Subscription {
    pub fn new(id: i32, status: models::SubscriptionStatusEnum, service: i32, service_hostname: String, subtotal: String, vat_value: String, total: String, creation_date: String) -> Subscription {
        Subscription {
            id,
            status,
            service,
            service_hostname,
            subtotal,
            vat_value,
            total,
            creation_date,
        }
    }
}

