/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuppressionEntry {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "reason")]
    pub reason: models::ReasonEnum,
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl SuppressionEntry {
    pub fn new(id: i32, address: String, reason: models::ReasonEnum, detail: String, created_at: String) -> SuppressionEntry {
        SuppressionEntry {
            id,
            address,
            reason,
            detail,
            created_at,
        }
    }
}

