/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TicketDetail {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "department")]
    pub department: Box<models::Department>,
    #[serde(rename = "priority")]
    pub priority: models::TicketPriorityEnum,
    #[serde(rename = "status")]
    pub status: models::TicketStatusEnum,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "updated")]
    pub updated: String,
    #[serde(rename = "messages")]
    pub messages: Vec<models::TicketMessage>,
}

impl TicketDetail {
    pub fn new(id: i32, subject: String, department: models::Department, priority: models::TicketPriorityEnum, status: models::TicketStatusEnum, created: String, updated: String, messages: Vec<models::TicketMessage>) -> TicketDetail {
        TicketDetail {
            id,
            subject,
            department: Box::new(department),
            priority,
            status,
            created,
            updated,
            messages,
        }
    }
}

