/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TicketMessage {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "author_name")]
    pub author_name: String,
    #[serde(rename = "has_attachment")]
    pub has_attachment: String,
    #[serde(rename = "attachment_filename")]
    pub attachment_filename: String,
}

impl TicketMessage {
    pub fn new(id: i32, date: String, message: String, author_name: String, has_attachment: String, attachment_filename: String) -> TicketMessage {
        TicketMessage {
            id,
            date,
            message,
            author_name,
            has_attachment,
            attachment_filename,
        }
    }
}

