/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tld {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "tld")]
    pub tld: String,
    /// Euro without TVA
    #[serde(rename = "price")]
    pub price: String,
    /// Euro without TVA
    #[serde(rename = "renew_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub renew_price: Option<Option<String>>,
    /// Euro without TVA
    #[serde(rename = "transfer_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transfer_price: Option<Option<String>>,
    #[serde(rename = "registrar")]
    pub registrar: String,
    #[serde(rename = "api_renewable", skip_serializing_if = "Option::is_none")]
    pub api_renewable: Option<bool>,
    #[serde(rename = "idna_support", skip_serializing_if = "Option::is_none")]
    pub idna_support: Option<bool>,
    #[serde(rename = "wg_support", skip_serializing_if = "Option::is_none")]
    pub wg_support: Option<bool>,
    #[serde(rename = "reactivate_max_days", skip_serializing_if = "Option::is_none")]
    pub reactivate_max_days: Option<i32>,
}

impl Tld {
    pub fn new(id: i32, tld: String, price: String, registrar: String) -> Tld {
        Tld {
            id,
            tld,
            price,
            renew_price: None,
            transfer_price: None,
            registrar,
            api_renewable: None,
            idna_support: None,
            wg_support: None,
            reactivate_max_days: None,
        }
    }
}

