/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToggleAutoPaymentResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "auto_payment")]
    pub auto_payment: bool,
}

impl ToggleAutoPaymentResponse {
    pub fn new(message: String, auto_payment: bool) -> ToggleAutoPaymentResponse {
        ToggleAutoPaymentResponse {
            message,
            auto_payment,
        }
    }
}

