/*
 * Pidgin Host API
 *
 * The Pidgin Host API allows you to manage Services and resources within the Pidgin Host cloud in a simple, programmatic way using conventional HTTP requests. All of the functionality that you are familiar with in the Pidgin Host control panel is also available through the API, allowing you to script the complex actions that your situation requires.
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Contact: support@pidginhost.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UdpRouteRequest : Serializer for UDPRoute resources with port validation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UdpRouteRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// External port to expose
    #[serde(rename = "port")]
    pub port: i32,
    /// Name of the backend Kubernetes Service
    #[serde(rename = "backend_service_name")]
    pub backend_service_name: String,
    /// Port of the backend Service
    #[serde(rename = "backend_service_port")]
    pub backend_service_port: i32,
    /// Namespace of the backend Service
    #[serde(rename = "backend_namespace", skip_serializing_if = "Option::is_none")]
    pub backend_namespace: Option<String>,
}

impl UdpRouteRequest {
    /// Serializer for UDPRoute resources with port validation.
    pub fn new(name: String, port: i32, backend_service_name: String, backend_service_port: i32) -> UdpRouteRequest {
        UdpRouteRequest {
            name,
            namespace: None,
            port,
            backend_service_name,
            backend_service_port,
            backend_namespace: None,
        }
    }
}

